GET http://localhost:5000

### login 
POST http://localhost:5000/auth/login


### register
POST http://localhost:5000/auth/register

### refesh-token
POST http://localhost:5000/auth/refesh-token

###logout
DELETE http://localhost:5000/auth/logout