GET http://localhost:5000

### login 
POST http://localhost:5000/auth/login


### register
POST http://localhost:5000/auth/register
Content-Type: application/json

{
    "email": "toiladuy2306@gmail.com",
    "password": "12345677"
}

### refesh-token
POST http://localhost:5000/auth/refesh-token

###logout
DELETE http://localhost:5000/auth/logout